[package]
name = "Flicker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
indicatif = "0.18.3"
anyhow = "1.0"
thiserror = "2.0.18"
sysinfo = "0.38.1"
sha2 = "0.10"
hex = "0.4"
libc = "0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true