#!/bin/sh
set -e

# Resolve the absolute path of this AppDir
HERE="$(dirname "$(readlink -f "${0}")")"

export APPDIR="${HERE}"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${HERE}/usr/lib64:${LD_LIBRARY_PATH}"
export XDG_DATA_DIRS="${HERE}/usr/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"

# Execute flicker binary
exec "${HERE}/usr/bin/flicker" "$@"
